compile:
	javac src/udp/*.java -d classes

	javac src/udp1/*.java -d classes

	javac src/udp2/*.java -d classes

runUdp:
	java -classpath classes udp.ReceiveUdp

runUdp1:
	java -classpath classes udp1.ReceiveUdp

runChat :
	java -classpath classes udp2.ChatReceive
